library(RMySQL)
library(Lahman)
require(DBI)

upload_lahman <- function(conn) {
  dbWriteTable(conn, name = "master", value = Master, append = TRUE, row.names = FALSE) # Added 3/5/2021
  dbWriteTable(conn, name = "people", value = People, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "batting", value = Batting, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "pitching", value = Pitching, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "fielding", value = Fielding, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "teams", value = Teams, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "teamsHalf", value = TeamsHalf, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "teamsFranchises", value = TeamsFranchises, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "battingPost", value = BattingPost, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "pitchingPost", value = PitchingPost, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "fieldingPost", value = FieldingPost, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "seriesPost", value = SeriesPost, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "awardsManagers", value = AwardsManagers, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "awardsPlayers", value = AwardsPlayers, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "awardsShareManagers", value = AwardsShareManagers, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "awardsSharePlayers", value = AwardsSharePlayers, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "hallOfFame", value = HallOfFame, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "allstarFull", value = AllstarFull, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "managers", value = Managers, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "fieldingOF", value = FieldingOF, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "managersHalf", value = ManagersHalf, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "salaries", value = Salaries, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "appearances", value = Appearances, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "schools", value = Schools, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "collegePlaying", value = CollegePlaying, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "battingLabels", value = battingLabels, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "pitchingLabels", value = pitchingLabels, append = TRUE, row.names = FALSE)
  dbWriteTable(conn, name = "fieldingLabels", value = fieldingLabels, append = TRUE, row.names = FALSE)
}
